FROM alpine:3.7

LABEL maintainer="Ryu Sato <ryu@weseek.co.jp>"
LABEL description="Build settings of utility container for initialize s3proxy in end to end test."

RUN apk add --no-cache \
    coreutils \
    bash \
    tzdata \
    curl

# install dockerize
ENV DOCKERIZE_VERSION v0.5.0
RUN curl -SL https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
      | tar -xz -C /usr/local/bin

# set timezone JST
RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
